Repository algorandfoundation/ARCs, pull requests merged in 2022-10, with the labels that each got.

#123 ARC4 - adding boxes
  ARCs/arc-0004.md
Labels: c-update

#142 Revert "ARC4 - adding boxes"
  ARCs/arc-0004.md
Labels: c-update, t-interface, s-stagnant

#97 Create ARC for extension of ARC-06 with account switch functionality
  ARCs/arc-0006.md
  ARCs/arc-0010.md
  ARCs/arc-0011.md
Labels: c-update, t-interface, s-final, s-stagnant

#138 Handle fewer accounts from requested
  ARCs/arc-0006.md
Labels: c-update, t-interface, s-stagnant
