Repository algorandfoundation/ARCs, pull requests merged in 2023-03, with the labels that each got.

#151 ARC-34 Governance proposal process
  ARCs/arc-0034.md
  assets/arc-0034/TemplateForm.md
  assets/arc-0034/application.py
Labels: t-meta, c-new

#152 ARC-33 Becoming an xGov
  ARCs/arc-0033.md
Labels: t-meta, c-new

#173 arc-72: remove tokenOfOwnerByIndex
  ARCs/arc-0072.md
Labels: c-update, t-interface

#180 Update arc-0015.md
  ARCs/arc-0015.md
Labels: c-update, t-interface

#184 Update Status ARCs 72 - 73 - 15 -22 -23
  ARCs/arc-0015.md
  ARCs/arc-0022.md
  ARCs/arc-0023.md
  ARCs/arc-0072.md
  ARCs/arc-0073.md
Labels: t-interface, s-final, s-stagnant, c-status
