Repository algorandfoundation/ARCs, pull requests merged in 2023-07, with the labels that each got.

#156 ARC-35: Secure Offline Wallet Backup Protocol
  ARCs/arc-0035.md
Labels: c-new, t-interface

#219 Adding arc number prefix to Application's method name
  ARCs/arc-0000.md
Labels: t-process

#227 arc-0048 Targeted Defi Rewards
  ARCs/arc-0048.md
Labels: c-new, t-informational

#228 arc-0049 NFT Rewards Terms & Conditions
  ARCs/arc-0049.md
Labels: c-new, t-informational
