Repository algorandfoundation/ARCs, pull requests merged in 2023-09, with the labels that each got.

#235 Update ARC-32: Update to match current implementation used by Beaker and algokit-utils
  ARCs/arc-0032.md
  assets/arc-0032/application.schema.json
  assets/arc-0032/contract.schema.json
Labels: s-draft, t-arc, c-update

#223 ARC-0200 draft
  ARCs/arc-0200.md
Labels: c-new, t-interface

#225 Adding method prename to arc-72
  ARCs/arc-0072.md
Labels: c-update, t-process
