Repository algorandfoundation/ARCs, pull requests merged in 2023-04, with the labels that each got.

#176 ARC-36: new metadata top-level field to support filters
  ARCs/arc-0036.md
Labels: w-stale, c-new, t-arc

#188 nit(arc-7): fix spelling mistakes
  ARCs/arc-0007.md
Labels: c-update, t-interface, s-final

#187 nit(arc-6): fix spelling mistakes
  ARCs/arc-0006.md
Labels: c-update, t-interface, s-final

#189 nit(arc-9): fix links & spelling
  ARCs/arc-0009.md
Labels: c-update, t-interface, s-final

#190 fix(arc-6): TS definitions are not valid TS
  ARCs/arc-0006.md
Labels: c-update, t-interface, s-final

#186 ARC - 33 xGov clarification
  ARCs/arc-0033.md
Labels: c-update, t-process

#170 ARC-74 Nft indexer API standard
  ARCs/arc-0074.md
Labels: s-draft, c-new, t-interface

#193 ARC-74 -> Last_Call
  ARCs/arc-0072.md
  ARCs/arc-0074.md
Labels: t-interface, c-status

#130 ARC-0012: Standard for Claimable Algorand Standard Assets (ASA)
  ARCs/arc-0012.md
  assets/arc-0012/README.md
  assets/arc-0012/arc12-sdk/.eslintrc.js
  assets/arc-0012/arc12-sdk/__tests__/clear.teal
  assets/arc-0012/arc12-sdk/__tests__/index.ts
  assets/arc-0012/arc12-sdk/jest.config.js
  assets/arc-0012/arc12-sdk/package-lock.json
  assets/arc-0012/arc12-sdk/package.json
  assets/arc-0012/arc12-sdk/src/index.ts
  assets/arc-0012/arc12-sdk/tsconfig.json
  assets/arc-0012/arc12-sdk/yarn.lock
  assets/arc-0012/contracts/Master.abi.json
  assets/arc-0012/contracts/Master.src_map.json
  assets/arc-0012/contracts/Master.teal
  assets/arc-0012/contracts/Vault.abi.json
  assets/arc-0012/contracts/Vault.src_map.json
  assets/arc-0012/contracts/Vault.teal
  assets/arc-0012/contracts/arc12.ts
  assets/arc-0012/contracts/package.json
  assets/arc-0012/contracts/tests/contracts.py
  assets/arc-0012/contracts/tests/fixtures.py
  assets/arc-0012/contracts/tests/pytest.ini
  assets/arc-0012/contracts/tests/requirements.txt
  assets/arc-0012/contracts/tests/test_arc12.py
  assets/arc-0012/contracts/tests/test_negatives.py
  assets/arc-0012/contracts/tests/test_reject.py
  assets/arc-0012/contracts/tests/test_two.py
  assets/arc-0012/contracts/tests/test_two_reject.py
  assets/arc-0012/contracts/tsconfig.json
  assets/arc-0012/contracts/yarn.lock
  assets/arc-0012/master.teal
  assets/arc-0012/vault.teal
Labels: s-draft, c-new, t-arc

#197 ARC-12 ASA Vault Finalization
  ARCs/arc-0012.md
  assets/arc-0012/README.md
Labels: t-arc, c-status
