Repository algorandfoundation/ARCs, pull requests merged in 2023-02, with the labels that each got.

#143 ARC15-ALGOSMS with Box Storage
  ARCs/arc-0015.md
  assets/arc-0015/application.py
  assets/arc-0015/main.py
Labels: c-new, t-interface

#164 add NFT standard draft arc-72
  ARCs/arc-0072.md
Labels: w-stale, s-draft, c-new, t-interface

#165 add interface detection draft arc-73
  ARCs/arc-0073.md
Labels: s-draft, c-new, t-interface
