Repository algorandfoundation/ARCs, pull requests merged in 2023-06, with the labels that each got.

#205 remove last-call-deadline
  ARCs/arc-0036.md
  ARCs/arc-0074.md
Labels: t-arc, c-update, t-interface, s-final

#206 fix: make `stxn` optional
  ARCs/arc-0001.md
Labels: c-update, t-interface, s-final

#209 Update Grants contract & payment ARC-34
  ARCs/arc-0034.md
Labels: c-update, t-process

#215 ARC-34 Disclaimer
  ARCs/arc-0034.md
Labels: c-update, t-process

#216 Format milestone part
  ARCs/arc-0034.md
Labels: c-update, t-process

#207 ARC-0076 - Password Account
  ARCs/arc-0076.md
Labels: c-new, t-core

#222 ARC-34 Updating milestone requirement
  ARCs/arc-0034.md
Labels: c-update, t-process
