Repository algorandfoundation/ARCs, pull requests merged in 2024-11, with the labels that each got.

#319 ARC-79, extends ARC-26 URI scheme with App NoOp calls
  ARCs/arc-0026.md
  ARCs/arc-0079.md
Labels: c-new, c-update, t-interface, s-final

#320 ARC-78: Scope, offline keyregs, params marked as required/optional
  ARCs/arc-0078.md
Labels: t-interface, s-final, c-status

#258 ARC56: Extended App Description
  ARCs/arc-0056.md
Labels: c-new, t-arc
