Repository algorandfoundation/ARCs, pull requests merged in 2024-03, with the labels that each got.

#204 arc-42 xGov dApp Integration
  ARCs/arc-0042.md
Labels: c-new, s-final, t-informational

#271 ARC-32 last call
  ARCs/arc-0032.md
Labels: t-arc, s-final, c-status

#287 Enforcing reference implementation
  ARCs/arc-0000.md
Labels: t-process

#274 ARC-55 updates
  ARCs/arc-0055.md
Labels: t-interface, s-final, c-status

#288 ARC-34 update for s4
  ARCs/arc-0034.md
Labels: c-update, t-process

#290 Add requirement to post proposal on the forum
  ARCs/arc-0034.md
Labels: c-update, t-process
