Repository algorandfoundation/ARCs, pull requests merged in 2024-10, with the labels that each got.

#302 ARC-62 - ASA Circulating Supply
  ARCs/arc-0062.md
  assets/arc-0062/.algokit.toml
  assets/arc-0062/.algokit/static-analysis/snapshots/CirculatingSupply.approval.json
  assets/arc-0062/.algokit/static-analysis/snapshots/CirculatingSupply.clear.json
  assets/arc-0062/.editorconfig
  assets/arc-0062/.gitattributes
  assets/arc-0062/.gitignore
  assets/arc-0062/.pre-commit-config.yaml
  assets/arc-0062/LICENSE
  assets/arc-0062/README.md
  assets/arc-0062/poetry.lock
  assets/arc-0062/poetry.toml
  assets/arc-0062/pyproject.toml
  assets/arc-0062/smart_contracts/__init__.py
  assets/arc-0062/smart_contracts/__main__.py
  assets/arc-0062/smart_contracts/_helpers/__init__.py
  assets/arc-0062/smart_contracts/_helpers/build.py
  assets/arc-0062/smart_contracts/_helpers/config.py
  assets/arc-0062/smart_contracts/_helpers/deploy.py
  assets/arc-0062/smart_contracts/artifacts/circulating_supply/CirculatingSupply.approval.teal
  assets/arc-0062/smart_contracts/artifacts/circulating_supply/CirculatingSupply.arc32.json
  assets/arc-0062/smart_contracts/artifacts/circulating_supply/CirculatingSupply.clear.teal
  assets/arc-0062/smart_contracts/artifacts/circulating_supply/circulating_supply_client.py
  assets/arc-0062/smart_contracts/circulating_supply/config.py
  assets/arc-0062/smart_contracts/circulating_supply/contract.py
  assets/arc-0062/smart_contracts/circulating_supply/deploy_config.py
  assets/arc-0062/smart_contracts/errors/__init__.py
  assets/arc-0062/smart_contracts/errors/std_errors.py
  assets/arc-0062/tests/__init__.py
  assets/arc-0062/tests/conftest.py
  assets/arc-0062/tests/test_deploy.py
  assets/arc-0062/tests/test_get_circulating_supply.py
  assets/arc-0062/tests/test_set_asset.py
  assets/arc-0062/tests/test_set_not_circulating_address.py
Labels: c-new, t-interface

#308 ARC-59 Status -> Final
  ARCs/arc-0059.md
Labels: t-arc, s-final, c-status

#318 ARC-0 Add Tracking mechanism for extension
  ARCs/arc-0000.md
Labels: t-process

#314 Arc 78, extends 26 URI scheme Key Reg
  ARCs/arc-0026.md
  ARCs/arc-0078.md
Labels: c-new, c-update, t-interface, s-final

#321 ARC-62 -> Final
  ARCs/arc-0062.md
Labels: t-interface, s-final, c-status
