Repository algorandfoundation/ARCs, pull requests merged in 2025-01, with the labels that each got.

#324 [ARC-82] Querying blockchain information using a URI format
  ARCs/arc-0082.md
Labels: c-new, t-arc

#179 ARC-0071: Soulbound ASA NFT
  ARCs/arc-0071.md
Labels: w-stale, c-new, t-interface

#329 [ARC-20] Reference implementation
  ARCs/arc-0020.md
  assets/arc-0020/.algokit.toml
  assets/arc-0020/.editorconfig
  assets/arc-0020/.gitattributes
  assets/arc-0020/.gitignore
  assets/arc-0020/.pre-commit-config.yaml
  assets/arc-0020/README.md
  assets/arc-0020/poetry.lock
  assets/arc-0020/poetry.toml
  assets/arc-0020/pyproject.toml
  assets/arc-0020/smart_contracts/__init__.py
  assets/arc-0020/smart_contracts/__main__.py
  assets/arc-0020/smart_contracts/_helpers/__init__.py
  assets/arc-0020/smart_contracts/_helpers/build.py
  assets/arc-0020/smart_contracts/_helpers/config.py
  assets/arc-0020/smart_contracts/_helpers/deploy.py
  assets/arc-0020/smart_contracts/artifacts/smart_asa/SmartAsa.approval.puya.map
  assets/arc-0020/smart_contracts/artifacts/smart_asa/SmartAsa.approval.teal
  assets/arc-0020/smart_contracts/artifacts/smart_asa/SmartAsa.arc32.json
  assets/arc-0020/smart_contracts/artifacts/smart_asa/SmartAsa.clear.puya.map
  assets/arc-0020/smart_contracts/artifacts/smart_asa/SmartAsa.clear.teal
  assets/arc-0020/smart_contracts/artifacts/smart_asa/smart_asa_client.py
  assets/arc-0020/smart_contracts/errors.py
  assets/arc-0020/smart_contracts/smart_asa/config.py
  assets/arc-0020/smart_contracts/smart_asa/contract.py
  assets/arc-0020/smart_contracts/smart_asa/deploy_config.py
  assets/arc-0020/smart_contracts/types.py
  assets/arc-0020/tests/__init__.py
  assets/arc-0020/tests/conftest.py
  assets/arc-0020/tests/test_account_freeze.py
  assets/arc-0020/tests/test_asset_close_out.py
  assets/arc-0020/tests/test_asset_config.py
  assets/arc-0020/tests/test_asset_create.py
  assets/arc-0020/tests/test_asset_destroy.py
  assets/arc-0020/tests/test_asset_freeze.py
  assets/arc-0020/tests/test_asset_opt_in.py
  assets/arc-0020/tests/test_asset_transfer.py
  assets/arc-0020/tests/test_deploy.py
  assets/arc-0020/tests/test_get_account_is_frozen.py
  assets/arc-0020/tests/test_get_asset_config.py
  assets/arc-0020/tests/test_get_asset_is_frozen.py
  assets/arc-0020/tests/test_get_circulating_supply.py
  assets/arc-0020/tests/utils.py
Labels: c-update, t-interface, s-final

#272 ARC-0027: Provider Message Schema
  ARCs/arc-0027.md
Labels: c-new, t-interface

#244 ARC-0053 Decentralized, Self-declared, & Verifiable Tokens, Collections, & Metadata
  ARCs/arc-0053.md
Labels: t-meta, c-new
